[package]
name = "nari-freetype"
workspace = ".."
version = "0.1.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]
keywords = ["freetype", "ffi"]
description = "Low level binding for FreeType font library"
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2.42"
