[workspace]
resolver = "2"
members = [
    "nari-freetype",
    "nari-gpu",
    "nari-ochre",
    "nari-canvas",
    "nari-platform",
    "nari-studio",
]

[workspace.dependencies]
nari-canvas = { path = "nari-canvas" }
nari-gpu = { path = "nari-gpu" }
nari-ochre = { path = "nari-ochre" }
nari-freetype = { path = "nari-freetype" }
