[workspace]
resolver = "2"
members = [
    "nari-freetype",
    "nari-platform",
    "nari-studio",
    "nari-vello",
    "nari-path",
]

[workspace.dependencies]
nari-freetype = { path = "nari-freetype" }
nari-platform = { path = "nari-platform" }
nari-vello = { path = "nari-vello" }

superluminal-perf = "0.2"
vello = { git = "https://github.com/msiglreith/vello.git", branch = "nari" }
swash = { git = "https://github.com/msiglreith/swash.git", branch = "nari" }
raw-window-handle = "0.5"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
