#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Codicon {
    Account,
    ActivateBreakpoints,
    Add,
    Alert,
    Archive,
    Array,
    ArrowBoth,
    ArrowCircleDown,
    ArrowCircleLeft,
    ArrowCircleRight,
    ArrowCircleUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowSmallDown,
    ArrowSmallLeft,
    ArrowSmallRight,
    ArrowSmallUp,
    ArrowSwap,
    ArrowUp,
    Azure,
    AzureDevops,
    Beaker,
    BeakerStop,
    Bell,
    BellDot,
    BellSlash,
    BellSlashDot,
    Blank,
    Bold,
    Book,
    Bookmark,
    Bracket,
    BracketDot,
    BracketError,
    Briefcase,
    Broadcast,
    Browser,
    Bug,
    Calendar,
    CallIncoming,
    CallOutgoing,
    CaseSensitive,
    Check,
    CheckAll,
    Checklist,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChromeClose,
    ChromeMaximize,
    ChromeMinimize,
    ChromeRestore,
    CircleFilled,
    CircleLargeFilled,
    CircleLargeOutline,
    CircleOutline,
    CircleSlash,
    CircleSmall,
    CircleSmallFilled,
    CircuitBoard,
    ClearAll,
    Clippy,
    Clock,
    Clone,
    Close,
    CloseAll,
    CloseDirty,
    Cloud,
    CloudDownload,
    CloudUpload,
    Code,
    CollapseAll,
    ColorMode,
    Combine,
    Comment,
    CommentAdd,
    CommentDiscussion,
    CommentUnresolved,
    CompareChanges,
    Compass,
    CompassActive,
    CompassDot,
    Console,
    Copy,
    CreditCard,
    Dash,
    Dashboard,
    Database,
    Debug,
    DebugAll,
    DebugAlt,
    DebugAltSmall,
    DebugBreakpoint,
    DebugBreakpointConditional,
    DebugBreakpointConditionalDisabled,
    DebugBreakpointConditionalUnverified,
    DebugBreakpointData,
    DebugBreakpointDataDisabled,
    DebugBreakpointDataUnverified,
    DebugBreakpointDisabled,
    DebugBreakpointFunction,
    DebugBreakpointFunctionDisabled,
    DebugBreakpointFunctionUnverified,
    DebugBreakpointLog,
    DebugBreakpointLogDisabled,
    DebugBreakpointLogUnverified,
    DebugBreakpointUnsupported,
    DebugBreakpointUnverified,
    DebugConsole,
    DebugContinue,
    DebugContinueSmall,
    DebugCoverage,
    DebugDisconnect,
    DebugHint,
    DebugLineByLine,
    DebugPause,
    DebugRerun,
    DebugRestart,
    DebugRestartFrame,
    DebugReverseContinue,
    DebugStackframe,
    DebugStackframeActive,
    DebugStackframeDot,
    DebugStackframeFocused,
    DebugStart,
    DebugStepBack,
    DebugStepInto,
    DebugStepOut,
    DebugStepOver,
    DebugStop,
    DesktopDownload,
    DeviceCamera,
    DeviceCameraVideo,
    DeviceDesktop,
    DeviceMobile,
    Diff,
    DiffAdded,
    DiffIgnored,
    DiffModified,
    DiffRemoved,
    DiffRenamed,
    Discard,
    Edit,
    EditorLayout,
    Ellipsis,
    EmptyWindow,
    Error,
    ErrorSmall,
    Exclude,
    ExpandAll,
    Export,
    Extensions,
    Eye,
    EyeClosed,
    EyeUnwatch,
    EyeWatch,
    Feedback,
    File,
    FileAdd,
    FileBinary,
    FileCode,
    FileDirectory,
    FileDirectoryCreate,
    FileMedia,
    FilePdf,
    FileSubmodule,
    FileSymlinkDirectory,
    FileSymlinkFile,
    FileText,
    FileZip,
    Files,
    Filter,
    FilterFilled,
    Flame,
    Fold,
    FoldDown,
    FoldUp,
    Folder,
    FolderActive,
    FolderLibrary,
    FolderOpened,
    Gather,
    Gear,
    Gift,
    Gist,
    GistFork,
    GistNew,
    GistPrivate,
    GistSecret,
    GitBranch,
    GitBranchCreate,
    GitBranchDelete,
    GitCommit,
    GitCompare,
    GitForkPrivate,
    GitMerge,
    GitPullRequest,
    GitPullRequestAbandoned,
    GitPullRequestClosed,
    GitPullRequestCreate,
    GitPullRequestDraft,
    GitPullRequestGoToChanges,
    GitPullRequestNewChanges,
    Github,
    GithubAction,
    GithubAlt,
    GithubInverted,
    Globe,
    GoToFile,
    Grabber,
    Graph,
    GraphLeft,
    GraphLine,
    GraphScatter,
    Gripper,
    GroupByRefType,
    Heart,
    HeartFilled,
    History,
    Home,
    HorizontalRule,
    Hubot,
    Inbox,
    Indent,
    Info,
    Inspect,
    IssueClosed,
    IssueDraft,
    IssueOpened,
    IssueReopened,
    Issues,
    Italic,
    Jersey,
    Json,
    KebabHorizontal,
    KebabVertical,
    Key,
    Keyboard,
    Law,
    Layers,
    LayersActive,
    LayersDot,
    Layout,
    LayoutActivitybarLeft,
    LayoutActivitybarRight,
    LayoutCentered,
    LayoutMenubar,
    LayoutPanel,
    LayoutPanelCenter,
    LayoutPanelJustify,
    LayoutPanelLeft,
    LayoutPanelOff,
    LayoutPanelRight,
    LayoutSidebarLeft,
    LayoutSidebarLeftOff,
    LayoutSidebarRight,
    LayoutSidebarRightOff,
    LayoutStatusbar,
    Library,
    LightBulb,
    Lightbulb,
    LightbulbAutofix,
    Link,
    LinkExternal,
    ListFilter,
    ListFlat,
    ListOrdered,
    ListSelection,
    ListTree,
    ListUnordered,
    LiveShare,
    Loading,
    Location,
    Lock,
    LockSmall,
    LogIn,
    LogOut,
    LogoGithub,
    Magnet,
    Mail,
    MailRead,
    MailReply,
    Map,
    MapFilled,
    MarkGithub,
    Markdown,
    Megaphone,
    Mention,
    Menu,
    Merge,
    Microscope,
    Milestone,
    Mirror,
    MirrorPrivate,
    MirrorPublic,
    More,
    MortarBoard,
    Move,
    MultipleWindows,
    Mute,
    NewFile,
    NewFolder,
    Newline,
    NoNewline,
    Note,
    Notebook,
    NotebookTemplate,
    Octoface,
    OpenPreview,
    Organization,
    OrganizationFilled,
    OrganizationOutline,
    Output,
    Package,
    Paintcan,
    Pass,
    PassFilled,
    Pencil,
    Person,
    PersonAdd,
    PersonFilled,
    PersonFollow,
    PersonOutline,
    PieChart,
    Pin,
    Pinned,
    PinnedDirty,
    Play,
    PlayCircle,
    Plug,
    Plus,
    PreserveCase,
    Preview,
    PrimitiveDot,
    PrimitiveSquare,
    Project,
    Pulse,
    Question,
    Quote,
    RadioTower,
    Reactions,
    Record,
    RecordKeys,
    RecordSmall,
    Redo,
    References,
    Refresh,
    Regex,
    Remote,
    RemoteExplorer,
    Remove,
    RemoveClose,
    Repl,
    Replace,
    ReplaceAll,
    Reply,
    Repo,
    RepoClone,
    RepoCreate,
    RepoDelete,
    RepoForcePush,
    RepoForked,
    RepoPull,
    RepoPush,
    RepoSync,
    Report,
    RequestChanges,
    Rocket,
    RootFolder,
    RootFolderOpened,
    Rss,
    Ruby,
    Run,
    RunAbove,
    RunAll,
    RunBelow,
    RunErrors,
    Save,
    SaveAll,
    SaveAs,
    ScreenFull,
    ScreenNormal,
    Search,
    SearchSave,
    SearchStop,
    Selection,
    Server,
    ServerEnvironment,
    ServerProcess,
    Settings,
    SettingsGear,
    Shield,
    SignIn,
    SignOut,
    Smiley,
    SortPrecedence,
    SourceControl,
    SplitHorizontal,
    SplitVertical,
    Squirrel,
    Star,
    StarAdd,
    StarDelete,
    StarEmpty,
    StarFull,
    StarHalf,
    Stop,
    StopCircle,
    SymbolArray,
    SymbolBoolean,
    SymbolClass,
    SymbolColor,
    SymbolConstant,
    SymbolConstructor,
    SymbolEnum,
    SymbolEnumMember,
    SymbolEvent,
    SymbolField,
    SymbolFile,
    SymbolFolder,
    SymbolFunction,
    SymbolInterface,
    SymbolKey,
    SymbolKeyword,
    SymbolMethod,
    SymbolMisc,
    SymbolModule,
    SymbolNamespace,
    SymbolNull,
    SymbolNumber,
    SymbolNumeric,
    SymbolObject,
    SymbolOperator,
    SymbolPackage,
    SymbolParameter,
    SymbolProperty,
    SymbolReference,
    SymbolRuler,
    SymbolSnippet,
    SymbolString,
    SymbolStruct,
    SymbolStructure,
    SymbolText,
    SymbolTypeParameter,
    SymbolUnit,
    SymbolValue,
    SymbolVariable,
    Sync,
    SyncIgnored,
    Table,
    Tag,
    TagAdd,
    TagRemove,
    Target,
    Tasklist,
    Telescope,
    Terminal,
    TerminalBash,
    TerminalCmd,
    TerminalDebian,
    TerminalLinux,
    TerminalPowershell,
    TerminalTmux,
    TerminalUbuntu,
    TextSize,
    ThreeBars,
    Thumbsdown,
    Thumbsup,
    Tools,
    Trash,
    Trashcan,
    TriangleDown,
    TriangleLeft,
    TriangleRight,
    TriangleUp,
    Twitter,
    TypeHierarchy,
    TypeHierarchySub,
    TypeHierarchySuper,
    Unfold,
    UngroupByRefType,
    Unlock,
    Unmute,
    Unverified,
    Variable,
    VariableGroup,
    Verified,
    VerifiedFilled,
    Versions,
    Vm,
    VmActive,
    VmConnect,
    VmOutline,
    VmRunning,
    Wand,
    Warning,
    Watch,
    Whitespace,
    WholeWord,
    Window,
    WordWrap,
    WorkspaceTrusted,
    WorkspaceUnknown,
    WorkspaceUntrusted,
    Wrench,
    WrenchSubaction,
    X,
    Zap,
    ZoomIn,
    ZoomOut,
}
impl AsRef<str> for Codicon {
    fn as_ref(&self) -> &'static str {
        match *self {
            Codicon::Account => "\u{eb99}",
            Codicon::ActivateBreakpoints => "\u{ea97}",
            Codicon::Add => "\u{ea60}",
            Codicon::Alert => "\u{ea6c}",
            Codicon::Archive => "\u{ea98}",
            Codicon::Array => "\u{ea8a}",
            Codicon::ArrowBoth => "\u{ea99}",
            Codicon::ArrowCircleDown => "\u{ebfc}",
            Codicon::ArrowCircleLeft => "\u{ebfd}",
            Codicon::ArrowCircleRight => "\u{ebfe}",
            Codicon::ArrowCircleUp => "\u{ebff}",
            Codicon::ArrowDown => "\u{ea9a}",
            Codicon::ArrowLeft => "\u{ea9b}",
            Codicon::ArrowRight => "\u{ea9c}",
            Codicon::ArrowSmallDown => "\u{ea9d}",
            Codicon::ArrowSmallLeft => "\u{ea9e}",
            Codicon::ArrowSmallRight => "\u{ea9f}",
            Codicon::ArrowSmallUp => "\u{eaa0}",
            Codicon::ArrowSwap => "\u{ebcb}",
            Codicon::ArrowUp => "\u{eaa1}",
            Codicon::Azure => "\u{ebd8}",
            Codicon::AzureDevops => "\u{ebe8}",
            Codicon::Beaker => "\u{ea79}",
            Codicon::BeakerStop => "\u{ebe1}",
            Codicon::Bell => "\u{eaa2}",
            Codicon::BellDot => "\u{eb9a}",
            Codicon::BellSlash => "\u{ec08}",
            Codicon::BellSlashDot => "\u{ec09}",
            Codicon::Blank => "\u{ec03}",
            Codicon::Bold => "\u{eaa3}",
            Codicon::Book => "\u{eaa4}",
            Codicon::Bookmark => "\u{eaa5}",
            Codicon::Bracket => "\u{eb0f}",
            Codicon::BracketDot => "\u{ebe5}",
            Codicon::BracketError => "\u{ebe6}",
            Codicon::Briefcase => "\u{eaac}",
            Codicon::Broadcast => "\u{eaad}",
            Codicon::Browser => "\u{eaae}",
            Codicon::Bug => "\u{eaaf}",
            Codicon::Calendar => "\u{eab0}",
            Codicon::CallIncoming => "\u{eb92}",
            Codicon::CallOutgoing => "\u{eb93}",
            Codicon::CaseSensitive => "\u{eab1}",
            Codicon::Check => "\u{eab2}",
            Codicon::CheckAll => "\u{ebb1}",
            Codicon::Checklist => "\u{eab3}",
            Codicon::ChevronDown => "\u{eab4}",
            Codicon::ChevronLeft => "\u{eab5}",
            Codicon::ChevronRight => "\u{eab6}",
            Codicon::ChevronUp => "\u{eab7}",
            Codicon::ChromeClose => "\u{eab8}",
            Codicon::ChromeMaximize => "\u{eab9}",
            Codicon::ChromeMinimize => "\u{eaba}",
            Codicon::ChromeRestore => "\u{eabb}",
            Codicon::CircleFilled => "\u{ea71}",
            Codicon::CircleLargeFilled => "\u{ebb4}",
            Codicon::CircleLargeOutline => "\u{ebb5}",
            Codicon::CircleOutline => "\u{eabc}",
            Codicon::CircleSlash => "\u{eabd}",
            Codicon::CircleSmall => "\u{ec07}",
            Codicon::CircleSmallFilled => "\u{eb8a}",
            Codicon::CircuitBoard => "\u{eabe}",
            Codicon::ClearAll => "\u{eabf}",
            Codicon::Clippy => "\u{eac0}",
            Codicon::Clock => "\u{ea82}",
            Codicon::Clone => "\u{ea78}",
            Codicon::Close => "\u{ea76}",
            Codicon::CloseAll => "\u{eac1}",
            Codicon::CloseDirty => "\u{ea71}",
            Codicon::Cloud => "\u{ebaa}",
            Codicon::CloudDownload => "\u{eac2}",
            Codicon::CloudUpload => "\u{eac3}",
            Codicon::Code => "\u{eac4}",
            Codicon::CollapseAll => "\u{eac5}",
            Codicon::ColorMode => "\u{eac6}",
            Codicon::Combine => "\u{ebb6}",
            Codicon::Comment => "\u{ea6b}",
            Codicon::CommentAdd => "\u{ea6b}",
            Codicon::CommentDiscussion => "\u{eac7}",
            Codicon::CommentUnresolved => "\u{ec0a}",
            Codicon::CompareChanges => "\u{eafd}",
            Codicon::Compass => "\u{ebd5}",
            Codicon::CompassActive => "\u{ebd7}",
            Codicon::CompassDot => "\u{ebd6}",
            Codicon::Console => "\u{ea85}",
            Codicon::Copy => "\u{ebcc}",
            Codicon::CreditCard => "\u{eac9}",
            Codicon::Dash => "\u{eacc}",
            Codicon::Dashboard => "\u{eacd}",
            Codicon::Database => "\u{eace}",
            Codicon::Debug => "\u{ead8}",
            Codicon::DebugAll => "\u{ebdc}",
            Codicon::DebugAlt => "\u{eb91}",
            Codicon::DebugAltSmall => "\u{eba8}",
            Codicon::DebugBreakpoint => "\u{ea71}",
            Codicon::DebugBreakpointConditional => "\u{eaa7}",
            Codicon::DebugBreakpointConditionalDisabled => "\u{eaa7}",
            Codicon::DebugBreakpointConditionalUnverified => "\u{eaa6}",
            Codicon::DebugBreakpointData => "\u{eaa9}",
            Codicon::DebugBreakpointDataDisabled => "\u{eaa9}",
            Codicon::DebugBreakpointDataUnverified => "\u{eaa8}",
            Codicon::DebugBreakpointDisabled => "\u{ea71}",
            Codicon::DebugBreakpointFunction => "\u{eb88}",
            Codicon::DebugBreakpointFunctionDisabled => "\u{eb88}",
            Codicon::DebugBreakpointFunctionUnverified => "\u{eb87}",
            Codicon::DebugBreakpointLog => "\u{eaab}",
            Codicon::DebugBreakpointLogDisabled => "\u{eaab}",
            Codicon::DebugBreakpointLogUnverified => "\u{eaaa}",
            Codicon::DebugBreakpointUnsupported => "\u{eb8c}",
            Codicon::DebugBreakpointUnverified => "\u{eabc}",
            Codicon::DebugConsole => "\u{eb9b}",
            Codicon::DebugContinue => "\u{eacf}",
            Codicon::DebugContinueSmall => "\u{ebe0}",
            Codicon::DebugCoverage => "\u{ebdd}",
            Codicon::DebugDisconnect => "\u{ead0}",
            Codicon::DebugHint => "\u{ea71}",
            Codicon::DebugLineByLine => "\u{ebd0}",
            Codicon::DebugPause => "\u{ead1}",
            Codicon::DebugRerun => "\u{ebc0}",
            Codicon::DebugRestart => "\u{ead2}",
            Codicon::DebugRestartFrame => "\u{eb90}",
            Codicon::DebugReverseContinue => "\u{eb8e}",
            Codicon::DebugStackframe => "\u{eb8b}",
            Codicon::DebugStackframeActive => "\u{eb89}",
            Codicon::DebugStackframeDot => "\u{eb8a}",
            Codicon::DebugStackframeFocused => "\u{eb8b}",
            Codicon::DebugStart => "\u{ead3}",
            Codicon::DebugStepBack => "\u{eb8f}",
            Codicon::DebugStepInto => "\u{ead4}",
            Codicon::DebugStepOut => "\u{ead5}",
            Codicon::DebugStepOver => "\u{ead6}",
            Codicon::DebugStop => "\u{ead7}",
            Codicon::DesktopDownload => "\u{ea78}",
            Codicon::DeviceCamera => "\u{eada}",
            Codicon::DeviceCameraVideo => "\u{ead9}",
            Codicon::DeviceDesktop => "\u{ea7a}",
            Codicon::DeviceMobile => "\u{eadb}",
            Codicon::Diff => "\u{eae1}",
            Codicon::DiffAdded => "\u{eadc}",
            Codicon::DiffIgnored => "\u{eadd}",
            Codicon::DiffModified => "\u{eade}",
            Codicon::DiffRemoved => "\u{eadf}",
            Codicon::DiffRenamed => "\u{eae0}",
            Codicon::Discard => "\u{eae2}",
            Codicon::Edit => "\u{ea73}",
            Codicon::EditorLayout => "\u{eae3}",
            Codicon::Ellipsis => "\u{ea7c}",
            Codicon::EmptyWindow => "\u{eae4}",
            Codicon::Error => "\u{ea87}",
            Codicon::ErrorSmall => "\u{ebfb}",
            Codicon::Exclude => "\u{eae5}",
            Codicon::ExpandAll => "\u{eb95}",
            Codicon::Export => "\u{ebac}",
            Codicon::Extensions => "\u{eae6}",
            Codicon::Eye => "\u{ea70}",
            Codicon::EyeClosed => "\u{eae7}",
            Codicon::EyeUnwatch => "\u{ea70}",
            Codicon::EyeWatch => "\u{ea70}",
            Codicon::Feedback => "\u{eb96}",
            Codicon::File => "\u{ea7b}",
            Codicon::FileAdd => "\u{ea7f}",
            Codicon::FileBinary => "\u{eae8}",
            Codicon::FileCode => "\u{eae9}",
            Codicon::FileDirectory => "\u{ea83}",
            Codicon::FileDirectoryCreate => "\u{ea80}",
            Codicon::FileMedia => "\u{eaea}",
            Codicon::FilePdf => "\u{eaeb}",
            Codicon::FileSubmodule => "\u{eaec}",
            Codicon::FileSymlinkDirectory => "\u{eaed}",
            Codicon::FileSymlinkFile => "\u{eaee}",
            Codicon::FileText => "\u{ea7b}",
            Codicon::FileZip => "\u{eaef}",
            Codicon::Files => "\u{eaf0}",
            Codicon::Filter => "\u{eaf1}",
            Codicon::FilterFilled => "\u{ebce}",
            Codicon::Flame => "\u{eaf2}",
            Codicon::Fold => "\u{eaf5}",
            Codicon::FoldDown => "\u{eaf3}",
            Codicon::FoldUp => "\u{eaf4}",
            Codicon::Folder => "\u{ea83}",
            Codicon::FolderActive => "\u{eaf6}",
            Codicon::FolderLibrary => "\u{ebdf}",
            Codicon::FolderOpened => "\u{eaf7}",
            Codicon::Gather => "\u{ebb6}",
            Codicon::Gear => "\u{eaf8}",
            Codicon::Gift => "\u{eaf9}",
            Codicon::Gist => "\u{eafb}",
            Codicon::GistFork => "\u{ea63}",
            Codicon::GistNew => "\u{ea60}",
            Codicon::GistPrivate => "\u{ea75}",
            Codicon::GistSecret => "\u{eafa}",
            Codicon::GitBranch => "\u{ea68}",
            Codicon::GitBranchCreate => "\u{ea68}",
            Codicon::GitBranchDelete => "\u{ea68}",
            Codicon::GitCommit => "\u{eafc}",
            Codicon::GitCompare => "\u{eafd}",
            Codicon::GitForkPrivate => "\u{ea75}",
            Codicon::GitMerge => "\u{eafe}",
            Codicon::GitPullRequest => "\u{ea64}",
            Codicon::GitPullRequestAbandoned => "\u{ea64}",
            Codicon::GitPullRequestClosed => "\u{ebda}",
            Codicon::GitPullRequestCreate => "\u{ebbc}",
            Codicon::GitPullRequestDraft => "\u{ebdb}",
            Codicon::GitPullRequestGoToChanges => "\u{ec0b}",
            Codicon::GitPullRequestNewChanges => "\u{ec0c}",
            Codicon::Github => "\u{ea84}",
            Codicon::GithubAction => "\u{eaff}",
            Codicon::GithubAlt => "\u{eb00}",
            Codicon::GithubInverted => "\u{eba1}",
            Codicon::Globe => "\u{eb01}",
            Codicon::GoToFile => "\u{ea94}",
            Codicon::Grabber => "\u{eb02}",
            Codicon::Graph => "\u{eb03}",
            Codicon::GraphLeft => "\u{ebad}",
            Codicon::GraphLine => "\u{ebe2}",
            Codicon::GraphScatter => "\u{ebe3}",
            Codicon::Gripper => "\u{eb04}",
            Codicon::GroupByRefType => "\u{eb97}",
            Codicon::Heart => "\u{eb05}",
            Codicon::HeartFilled => "\u{ec04}",
            Codicon::History => "\u{ea82}",
            Codicon::Home => "\u{eb06}",
            Codicon::HorizontalRule => "\u{eb07}",
            Codicon::Hubot => "\u{eb08}",
            Codicon::Inbox => "\u{eb09}",
            Codicon::Indent => "\u{ebf9}",
            Codicon::Info => "\u{ea74}",
            Codicon::Inspect => "\u{ebd1}",
            Codicon::IssueClosed => "\u{eba4}",
            Codicon::IssueDraft => "\u{ebd9}",
            Codicon::IssueOpened => "\u{ea74}",
            Codicon::IssueReopened => "\u{eb0b}",
            Codicon::Issues => "\u{eb0c}",
            Codicon::Italic => "\u{eb0d}",
            Codicon::Jersey => "\u{eb0e}",
            Codicon::Json => "\u{eb0f}",
            Codicon::KebabHorizontal => "\u{ea7c}",
            Codicon::KebabVertical => "\u{eb10}",
            Codicon::Key => "\u{eb11}",
            Codicon::Keyboard => "\u{ea65}",
            Codicon::Law => "\u{eb12}",
            Codicon::Layers => "\u{ebd2}",
            Codicon::LayersActive => "\u{ebd4}",
            Codicon::LayersDot => "\u{ebd3}",
            Codicon::Layout => "\u{ebeb}",
            Codicon::LayoutActivitybarLeft => "\u{ebec}",
            Codicon::LayoutActivitybarRight => "\u{ebed}",
            Codicon::LayoutCentered => "\u{ebf7}",
            Codicon::LayoutMenubar => "\u{ebf6}",
            Codicon::LayoutPanel => "\u{ebf2}",
            Codicon::LayoutPanelCenter => "\u{ebef}",
            Codicon::LayoutPanelJustify => "\u{ebf0}",
            Codicon::LayoutPanelLeft => "\u{ebee}",
            Codicon::LayoutPanelOff => "\u{ec01}",
            Codicon::LayoutPanelRight => "\u{ebf1}",
            Codicon::LayoutSidebarLeft => "\u{ebf3}",
            Codicon::LayoutSidebarLeftOff => "\u{ec02}",
            Codicon::LayoutSidebarRight => "\u{ebf4}",
            Codicon::LayoutSidebarRightOff => "\u{ec00}",
            Codicon::LayoutStatusbar => "\u{ebf5}",
            Codicon::Library => "\u{eb9c}",
            Codicon::LightBulb => "\u{ea61}",
            Codicon::Lightbulb => "\u{ea61}",
            Codicon::LightbulbAutofix => "\u{eb13}",
            Codicon::Link => "\u{eb15}",
            Codicon::LinkExternal => "\u{eb14}",
            Codicon::ListFilter => "\u{eb83}",
            Codicon::ListFlat => "\u{eb84}",
            Codicon::ListOrdered => "\u{eb16}",
            Codicon::ListSelection => "\u{eb85}",
            Codicon::ListTree => "\u{eb86}",
            Codicon::ListUnordered => "\u{eb17}",
            Codicon::LiveShare => "\u{eb18}",
            Codicon::Loading => "\u{eb19}",
            Codicon::Location => "\u{eb1a}",
            Codicon::Lock => "\u{ea75}",
            Codicon::LockSmall => "\u{ebe7}",
            Codicon::LogIn => "\u{ea6f}",
            Codicon::LogOut => "\u{ea6e}",
            Codicon::LogoGithub => "\u{ea84}",
            Codicon::Magnet => "\u{ebae}",
            Codicon::Mail => "\u{eb1c}",
            Codicon::MailRead => "\u{eb1b}",
            Codicon::MailReply => "\u{ea7d}",
            Codicon::Map => "\u{ec05}",
            Codicon::MapFilled => "\u{ec06}",
            Codicon::MarkGithub => "\u{ea84}",
            Codicon::Markdown => "\u{eb1d}",
            Codicon::Megaphone => "\u{eb1e}",
            Codicon::Mention => "\u{eb1f}",
            Codicon::Menu => "\u{eb94}",
            Codicon::Merge => "\u{ebab}",
            Codicon::Microscope => "\u{ea79}",
            Codicon::Milestone => "\u{eb20}",
            Codicon::Mirror => "\u{ea69}",
            Codicon::MirrorPrivate => "\u{ea75}",
            Codicon::MirrorPublic => "\u{ea69}",
            Codicon::More => "\u{ea7c}",
            Codicon::MortarBoard => "\u{eb21}",
            Codicon::Move => "\u{eb22}",
            Codicon::MultipleWindows => "\u{eb23}",
            Codicon::Mute => "\u{eb24}",
            Codicon::NewFile => "\u{ea7f}",
            Codicon::NewFolder => "\u{ea80}",
            Codicon::Newline => "\u{ebea}",
            Codicon::NoNewline => "\u{eb25}",
            Codicon::Note => "\u{eb26}",
            Codicon::Notebook => "\u{ebaf}",
            Codicon::NotebookTemplate => "\u{ebbf}",
            Codicon::Octoface => "\u{eb27}",
            Codicon::OpenPreview => "\u{eb28}",
            Codicon::Organization => "\u{ea7e}",
            Codicon::OrganizationFilled => "\u{ea7e}",
            Codicon::OrganizationOutline => "\u{ea7e}",
            Codicon::Output => "\u{eb9d}",
            Codicon::Package => "\u{eb29}",
            Codicon::Paintcan => "\u{eb2a}",
            Codicon::Pass => "\u{eba4}",
            Codicon::PassFilled => "\u{ebb3}",
            Codicon::Pencil => "\u{ea73}",
            Codicon::Person => "\u{ea67}",
            Codicon::PersonAdd => "\u{ebcd}",
            Codicon::PersonFilled => "\u{ea67}",
            Codicon::PersonFollow => "\u{ea67}",
            Codicon::PersonOutline => "\u{ea67}",
            Codicon::PieChart => "\u{ebe4}",
            Codicon::Pin => "\u{eb2b}",
            Codicon::Pinned => "\u{eba0}",
            Codicon::PinnedDirty => "\u{ebb2}",
            Codicon::Play => "\u{eb2c}",
            Codicon::PlayCircle => "\u{eba6}",
            Codicon::Plug => "\u{eb2d}",
            Codicon::Plus => "\u{ea60}",
            Codicon::PreserveCase => "\u{eb2e}",
            Codicon::Preview => "\u{eb2f}",
            Codicon::PrimitiveDot => "\u{ea71}",
            Codicon::PrimitiveSquare => "\u{ea72}",
            Codicon::Project => "\u{eb30}",
            Codicon::Pulse => "\u{eb31}",
            Codicon::Question => "\u{eb32}",
            Codicon::Quote => "\u{eb33}",
            Codicon::RadioTower => "\u{eb34}",
            Codicon::Reactions => "\u{eb35}",
            Codicon::Record => "\u{eba7}",
            Codicon::RecordKeys => "\u{ea65}",
            Codicon::RecordSmall => "\u{ebfa}",
            Codicon::Redo => "\u{ebb0}",
            Codicon::References => "\u{eb36}",
            Codicon::Refresh => "\u{eb37}",
            Codicon::Regex => "\u{eb38}",
            Codicon::Remote => "\u{eb3a}",
            Codicon::RemoteExplorer => "\u{eb39}",
            Codicon::Remove => "\u{eb3b}",
            Codicon::RemoveClose => "\u{ea76}",
            Codicon::Repl => "\u{ea85}",
            Codicon::Replace => "\u{eb3d}",
            Codicon::ReplaceAll => "\u{eb3c}",
            Codicon::Reply => "\u{ea7d}",
            Codicon::Repo => "\u{ea62}",
            Codicon::RepoClone => "\u{eb3e}",
            Codicon::RepoCreate => "\u{ea60}",
            Codicon::RepoDelete => "\u{ea62}",
            Codicon::RepoForcePush => "\u{eb3f}",
            Codicon::RepoForked => "\u{ea63}",
            Codicon::RepoPull => "\u{eb40}",
            Codicon::RepoPush => "\u{eb41}",
            Codicon::RepoSync => "\u{ea77}",
            Codicon::Report => "\u{eb42}",
            Codicon::RequestChanges => "\u{eb43}",
            Codicon::Rocket => "\u{eb44}",
            Codicon::RootFolder => "\u{eb46}",
            Codicon::RootFolderOpened => "\u{eb45}",
            Codicon::Rss => "\u{eb47}",
            Codicon::Ruby => "\u{eb48}",
            Codicon::Run => "\u{eb2c}",
            Codicon::RunAbove => "\u{ebbd}",
            Codicon::RunAll => "\u{eb9e}",
            Codicon::RunBelow => "\u{ebbe}",
            Codicon::RunErrors => "\u{ebde}",
            Codicon::Save => "\u{eb4b}",
            Codicon::SaveAll => "\u{eb49}",
            Codicon::SaveAs => "\u{eb4a}",
            Codicon::ScreenFull => "\u{eb4c}",
            Codicon::ScreenNormal => "\u{eb4d}",
            Codicon::Search => "\u{ea6d}",
            Codicon::SearchSave => "\u{ea6d}",
            Codicon::SearchStop => "\u{eb4e}",
            Codicon::Selection => "\u{eb85}",
            Codicon::Server => "\u{eb50}",
            Codicon::ServerEnvironment => "\u{eba3}",
            Codicon::ServerProcess => "\u{eba2}",
            Codicon::Settings => "\u{eb52}",
            Codicon::SettingsGear => "\u{eb51}",
            Codicon::Shield => "\u{eb53}",
            Codicon::SignIn => "\u{ea6f}",
            Codicon::SignOut => "\u{ea6e}",
            Codicon::Smiley => "\u{eb54}",
            Codicon::SortPrecedence => "\u{eb55}",
            Codicon::SourceControl => "\u{ea68}",
            Codicon::SplitHorizontal => "\u{eb56}",
            Codicon::SplitVertical => "\u{eb57}",
            Codicon::Squirrel => "\u{eb58}",
            Codicon::Star => "\u{ea6a}",
            Codicon::StarAdd => "\u{ea6a}",
            Codicon::StarDelete => "\u{ea6a}",
            Codicon::StarEmpty => "\u{ea6a}",
            Codicon::StarFull => "\u{eb59}",
            Codicon::StarHalf => "\u{eb5a}",
            Codicon::Stop => "\u{ea87}",
            Codicon::StopCircle => "\u{eba5}",
            Codicon::SymbolArray => "\u{ea8a}",
            Codicon::SymbolBoolean => "\u{ea8f}",
            Codicon::SymbolClass => "\u{eb5b}",
            Codicon::SymbolColor => "\u{eb5c}",
            Codicon::SymbolConstant => "\u{eb5d}",
            Codicon::SymbolConstructor => "\u{ea8c}",
            Codicon::SymbolEnum => "\u{ea95}",
            Codicon::SymbolEnumMember => "\u{eb5e}",
            Codicon::SymbolEvent => "\u{ea86}",
            Codicon::SymbolField => "\u{eb5f}",
            Codicon::SymbolFile => "\u{eb60}",
            Codicon::SymbolFolder => "\u{ea83}",
            Codicon::SymbolFunction => "\u{ea8c}",
            Codicon::SymbolInterface => "\u{eb61}",
            Codicon::SymbolKey => "\u{ea93}",
            Codicon::SymbolKeyword => "\u{eb62}",
            Codicon::SymbolMethod => "\u{ea8c}",
            Codicon::SymbolMisc => "\u{eb63}",
            Codicon::SymbolModule => "\u{ea8b}",
            Codicon::SymbolNamespace => "\u{ea8b}",
            Codicon::SymbolNull => "\u{ea8f}",
            Codicon::SymbolNumber => "\u{ea90}",
            Codicon::SymbolNumeric => "\u{ea90}",
            Codicon::SymbolObject => "\u{ea8b}",
            Codicon::SymbolOperator => "\u{eb64}",
            Codicon::SymbolPackage => "\u{ea8b}",
            Codicon::SymbolParameter => "\u{ea92}",
            Codicon::SymbolProperty => "\u{eb65}",
            Codicon::SymbolReference => "\u{ea94}",
            Codicon::SymbolRuler => "\u{ea96}",
            Codicon::SymbolSnippet => "\u{eb66}",
            Codicon::SymbolString => "\u{eb8d}",
            Codicon::SymbolStruct => "\u{ea91}",
            Codicon::SymbolStructure => "\u{ea91}",
            Codicon::SymbolText => "\u{ea93}",
            Codicon::SymbolTypeParameter => "\u{ea92}",
            Codicon::SymbolUnit => "\u{ea96}",
            Codicon::SymbolValue => "\u{ea95}",
            Codicon::SymbolVariable => "\u{ea88}",
            Codicon::Sync => "\u{ea77}",
            Codicon::SyncIgnored => "\u{eb9f}",
            Codicon::Table => "\u{ebb7}",
            Codicon::Tag => "\u{ea66}",
            Codicon::TagAdd => "\u{ea66}",
            Codicon::TagRemove => "\u{ea66}",
            Codicon::Target => "\u{ebf8}",
            Codicon::Tasklist => "\u{eb67}",
            Codicon::Telescope => "\u{eb68}",
            Codicon::Terminal => "\u{ea85}",
            Codicon::TerminalBash => "\u{ebca}",
            Codicon::TerminalCmd => "\u{ebc4}",
            Codicon::TerminalDebian => "\u{ebc5}",
            Codicon::TerminalLinux => "\u{ebc6}",
            Codicon::TerminalPowershell => "\u{ebc7}",
            Codicon::TerminalTmux => "\u{ebc8}",
            Codicon::TerminalUbuntu => "\u{ebc9}",
            Codicon::TextSize => "\u{eb69}",
            Codicon::ThreeBars => "\u{eb6a}",
            Codicon::Thumbsdown => "\u{eb6b}",
            Codicon::Thumbsup => "\u{eb6c}",
            Codicon::Tools => "\u{eb6d}",
            Codicon::Trash => "\u{ea81}",
            Codicon::Trashcan => "\u{ea81}",
            Codicon::TriangleDown => "\u{eb6e}",
            Codicon::TriangleLeft => "\u{eb6f}",
            Codicon::TriangleRight => "\u{eb70}",
            Codicon::TriangleUp => "\u{eb71}",
            Codicon::Twitter => "\u{eb72}",
            Codicon::TypeHierarchy => "\u{ebb9}",
            Codicon::TypeHierarchySub => "\u{ebba}",
            Codicon::TypeHierarchySuper => "\u{ebbb}",
            Codicon::Unfold => "\u{eb73}",
            Codicon::UngroupByRefType => "\u{eb98}",
            Codicon::Unlock => "\u{eb74}",
            Codicon::Unmute => "\u{eb75}",
            Codicon::Unverified => "\u{eb76}",
            Codicon::Variable => "\u{ea88}",
            Codicon::VariableGroup => "\u{ebb8}",
            Codicon::Verified => "\u{eb77}",
            Codicon::VerifiedFilled => "\u{ebe9}",
            Codicon::Versions => "\u{eb78}",
            Codicon::Vm => "\u{ea7a}",
            Codicon::VmActive => "\u{eb79}",
            Codicon::VmConnect => "\u{eba9}",
            Codicon::VmOutline => "\u{eb7a}",
            Codicon::VmRunning => "\u{eb7b}",
            Codicon::Wand => "\u{ebcf}",
            Codicon::Warning => "\u{ea6c}",
            Codicon::Watch => "\u{eb7c}",
            Codicon::Whitespace => "\u{eb7d}",
            Codicon::WholeWord => "\u{eb7e}",
            Codicon::Window => "\u{eb7f}",
            Codicon::WordWrap => "\u{eb80}",
            Codicon::WorkspaceTrusted => "\u{ebc1}",
            Codicon::WorkspaceUnknown => "\u{ebc3}",
            Codicon::WorkspaceUntrusted => "\u{ebc2}",
            Codicon::Wrench => "\u{eb65}",
            Codicon::WrenchSubaction => "\u{eb65}",
            Codicon::X => "\u{ea76}",
            Codicon::Zap => "\u{ea86}",
            Codicon::ZoomIn => "\u{eb81}",
            Codicon::ZoomOut => "\u{eb82}",
        }
    }
}
