[package]
name = "nari-path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.2"
nari-platform.workspace = true
nari-vello.workspace = true
kurbo = "0.9"
bacon-sci = "0.13"