[package]
name = "nari-gpu"
version = "0.1.0"
edition = "2021"
workspace = ".."

[lib]

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
gpu-allocator = "0.27.0"

raw-window-handle.workspace = true
anyhow.workspace = true # remove

[dev-dependencies]
nari-platform.workspace = true